### PR TITLE
created player class with 3 lives

### PR DESCRIPTION
**Pull request by Ovillena**
Issue #1 

@whitebread778 
created a player class for issue #1

### CODE REVIEW

**Review by whitebread778 — CHANGES_REQUESTED** [review]
Good job Octavio.
But could you please check the lives you gave to the player?
We can not earn money if you gave the player too many lives!

**Review by whitebread778 — APPROVED** [review]
Good!

**Comment by Ovillena** [comment]
Hey @whitebread778, sorry it seems like my 3 button is broken. I think the company needs to pay for my new keyboard. can you check the changes again?

**Comment by Ovillena** [comment]
oh you merged it. nvm. Thanks!

**Pull request merged**
